//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryWebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.AppliedService = new HashSet<AppliedService>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int OrderStatusId { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> BarcodeId { get; set; }
    
        public virtual BarcodeOfPatient BarcodeOfPatient { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual StatusOfOrder StatusOfOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedService> AppliedService { get; set; }
    }
}
